# https://docs.travis-ci.com/user/languages/go/
dist: bionic
language: go
go_import_path: github.com/jeremyje/filetools

env:
  global:
  - GO111MODULE="on"

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12
  - master

os:
  - linux
  - osx
  - windows

script:
  - make all
  - make check
